[project]
name = "liminatr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "pycodestyle>=2.14.0",
    "tqdm>=4.67.1",
]
